import { layoutForLook } from "@/lib/generator/layout";
import type { LookPiece } from "@/lib/generator/types";

/** How many pieces onboarding asks for first — `onboarding/capture/page.tsx` fills five boxes (`.limit(5)`). */
export const STARTER_PIECES = 5;

export type ExamplePieceKey =
  | "navySweater" | "whiteTrousers" | "whiteSneakers" | "watch" | "blueShirt"
  | "stoneTrousers" | "creamSneakers" | "creamPolo" | "lightJeans" | "paleBlueSneakers";

type ExamplePiece = { category: "Tops" | "Bottoms" | "Shoes" | "Accessories"; src: string; colors: string[] };

/** The owner's own garments (public/landing, generated by scripts/landing-assets.mjs). */
export const EXAMPLE_PIECES: Record<ExamplePieceKey, ExamplePiece> = {
  navySweater: { category: "Tops", src: "/landing/navy-sweater.webp", colors: ["navy"] },
  whiteTrousers: { category: "Bottoms", src: "/landing/white-trousers.webp", colors: ["white"] },
  whiteSneakers: { category: "Shoes", src: "/landing/white-sneakers.webp", colors: ["white"] },
  watch: { category: "Accessories", src: "/landing/watch.webp", colors: ["silver"] },
  blueShirt: { category: "Tops", src: "/landing/blue-shirt.webp", colors: ["sky"] },
  stoneTrousers: { category: "Bottoms", src: "/landing/stone-trousers.webp", colors: ["stone"] },
  creamSneakers: { category: "Shoes", src: "/landing/cream-sneakers.webp", colors: ["cream"] },
  creamPolo: { category: "Tops", src: "/landing/cream-knit-polo.webp", colors: ["cream"] },
  lightJeans: { category: "Bottoms", src: "/landing/light-jeans.webp", colors: ["denim"] },
  paleBlueSneakers: { category: "Shoes", src: "/landing/pale-blue-sneakers.webp", colors: ["sky", "white"] },
};

export type ExampleLookKey = "quietNavy" | "blueStone" | "creamDenim";

/** A representative daily set — names and "why" lines are written in the stylist's voice and labelled "Example". */
export const EXAMPLE_LOOKS: readonly { key: ExampleLookKey; pieces: readonly ExamplePieceKey[] }[] = [
  { key: "quietNavy", pieces: ["navySweater", "whiteTrousers", "whiteSneakers", "watch"] },
  { key: "blueStone", pieces: ["blueShirt", "stoneTrousers", "creamSneakers"] },
  { key: "creamDenim", pieces: ["creamPolo", "lightJeans", "paleBlueSneakers"] },
];

/** The example closet in grid order. */
export const EXAMPLE_CLOSET: readonly ExamplePieceKey[] = [
  "navySweater", "blueShirt", "creamPolo", "whiteTrousers", "stoneTrousers",
  "lightJeans", "whiteSneakers", "creamSneakers", "watch",
];

/** The example day: 16° now, feels 15°, up to 19° — mild enough that a knit is right. */
export const EXAMPLE_WEATHER = { tempC: 16, feelsC: 15, highC: 19 } as const;

/** Example pieces placed exactly as the app places a real look. */
export function exampleLookPieces(keys: readonly ExamplePieceKey[], name: (key: ExamplePieceKey) => string): LookPiece[] {
  const pieces = keys.map((key) => ({
    itemId: `example-${key}`,
    category: EXAMPLE_PIECES[key].category,
    subcategory: null,
    brand: null,
    name: name(key),
    colors: EXAMPLE_PIECES[key].colors,
    cutoutUrl: EXAMPLE_PIECES[key].src,
  }));
  const slots = layoutForLook(pieces);
  return pieces.map((piece, i) => ({ ...piece, slot: slots[i] }));
}
